{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"symbolKind":"case","title":"ParseError.internalError(_:)","roleHeading":"Case","modules":[{"name":"GnustoEngine"}],"role":"symbol","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF"},"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","url":"\/documentation\/gnustoengine","kind":"symbol","abstract":[],"title":"GnustoEngine","role":"collection"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"title":"ParseError","role":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ParseError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ParseError","kind":"identifier"}],"abstract":[{"text":"Enumerates errors that can occur during the command parsing phase.","type":"text"}],"type":"topic","url":"\/documentation\/gnustoengine\/parseerror"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"role":"symbol","title":"ParseError.internalError(_:)","type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"}}}