{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","symbolKind":"case","title":"ActionResponse.internalEngineError(_:)","modules":[{"name":"GnustoEngine"}],"roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"title":"ActionResponse","kind":"symbol","abstract":[{"text":"Enumerates standard reasons why a game action might fail or be disallowed.","type":"text"}],"type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","url":"\/documentation\/gnustoengine\/actionresponse","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"title":"ActionResponse.internalEngineError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"role":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","abstract":[],"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","url":"\/documentation\/gnustoengine","kind":"symbol","type":"topic"}}}