{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"metadata":{"modules":[{"name":"GnustoEngine"}],"roleHeading":"Case","role":"symbol","title":"ActionResponse.internalEngineError(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","url":"\/documentation\/gnustoengine\/actionresponse","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"role":"symbol","kind":"symbol","title":"ActionResponse","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}]},"doc://GnustoEngine/documentation/GnustoEngine":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","url":"\/documentation\/gnustoengine","kind":"symbol","abstract":[],"title":"GnustoEngine","role":"collection"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","type":"topic","role":"symbol","title":"ActionResponse.internalEngineError(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","kind":"symbol"}}}