{"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","title":"ActionResponse.internalEngineError(_:)","symbolKind":"case","role":"symbol","modules":[{"name":"GnustoEngine"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"An unexpected internal error occurred within the engine or an action handler."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"kind":"symbol","abstract":[{"text":"Enumerates errors that can occur during the execution phase of a command.","type":"text"}],"navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionResponse","kind":"identifier"}],"title":"ActionResponse","url":"\/documentation\/gnustoengine\/actionresponse","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine":{"type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","abstract":[],"url":"\/documentation\/gnustoengine","title":"GnustoEngine","role":"collection","kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"text":"An unexpected internal error occurred within the engine or an action handler.","type":"text"}],"title":"ActionResponse.internalEngineError(_:)"}}}